name: CI

on:
  push:
    branches:
      - main
      - solucion
      - 'feature/*'
      - 'develop'
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      # Build the Docker containers
      - name: Build Containers
        run: docker-compose build --no-cache

      # Run backend tests inside the container
      - name: Run Backend Tests in Container
        run: docker-compose run --rm backend sh -c "cd /app && pytest --maxfail=1 --disable-warnings -q"